//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Learning_Management_System.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("English_Learning_Management_System.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_076b156fd1bef568fd048361114e5be5eg {
            get {
                object obj = ResourceManager.GetObject("Whisk_076b156fd1bef568fd048361114e5be5eg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_0bf6430918b1f5daae84ab013223a4a5dr {
            get {
                object obj = ResourceManager.GetObject("Whisk_0bf6430918b1f5daae84ab013223a4a5dr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_129c13e609585c5a034470c1ca88eddedr {
            get {
                object obj = ResourceManager.GetObject("Whisk_129c13e609585c5a034470c1ca88eddedr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_15939799505bc0cb8044a9d2c83a4d19dr {
            get {
                object obj = ResourceManager.GetObject("Whisk_15939799505bc0cb8044a9d2c83a4d19dr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_1669068d1a729e2a0e34795a81fb5a40dr {
            get {
                object obj = ResourceManager.GetObject("Whisk_1669068d1a729e2a0e34795a81fb5a40dr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_20e41b3c874b33d9ae94b983270bb25beg {
            get {
                object obj = ResourceManager.GetObject("Whisk_20e41b3c874b33d9ae94b983270bb25beg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_311aac7ad8568228d29447fcf1b7dc93dr {
            get {
                object obj = ResourceManager.GetObject("Whisk_311aac7ad8568228d29447fcf1b7dc93dr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_3394e9a0b86546a88b841d1cc3de004adr {
            get {
                object obj = ResourceManager.GetObject("Whisk_3394e9a0b86546a88b841d1cc3de004adr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_3e207dfd0bd7267b30041496d6aa7cf9dr {
            get {
                object obj = ResourceManager.GetObject("Whisk_3e207dfd0bd7267b30041496d6aa7cf9dr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_3ecf997d7e6d1a5862a42ef70cb64c95eg {
            get {
                object obj = ResourceManager.GetObject("Whisk_3ecf997d7e6d1a5862a42ef70cb64c95eg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_464189a0601ec149fd841f6c137a8e2edr {
            get {
                object obj = ResourceManager.GetObject("Whisk_464189a0601ec149fd841f6c137a8e2edr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_48b8f730db7cef7bbed435fed23e115edr {
            get {
                object obj = ResourceManager.GetObject("Whisk_48b8f730db7cef7bbed435fed23e115edr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_5492df75a0d22f3b4ff404404595b627dr {
            get {
                object obj = ResourceManager.GetObject("Whisk_5492df75a0d22f3b4ff404404595b627dr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_5952a128da5ba2d81e44bf130280d6d9dr {
            get {
                object obj = ResourceManager.GetObject("Whisk_5952a128da5ba2d81e44bf130280d6d9dr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_5f815065315d09592be4f3ec4ab8d974eg {
            get {
                object obj = ResourceManager.GetObject("Whisk_5f815065315d09592be4f3ec4ab8d974eg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_6aba0891d35a9dcad954bf110b95ef8ddr {
            get {
                object obj = ResourceManager.GetObject("Whisk_6aba0891d35a9dcad954bf110b95ef8ddr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_6eeff68830bbca59d794a6bf4cc3afd7dr {
            get {
                object obj = ResourceManager.GetObject("Whisk_6eeff68830bbca59d794a6bf4cc3afd7dr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_79977cb11a3ae07b0804415d6a87e69ceg {
            get {
                object obj = ResourceManager.GetObject("Whisk_79977cb11a3ae07b0804415d6a87e69ceg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_79977cb11a3ae07b0804415d6a87e69ceg__1_ {
            get {
                object obj = ResourceManager.GetObject("Whisk_79977cb11a3ae07b0804415d6a87e69ceg (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_7a2731d0a50dfd5b1424fb307dcf5f16dr {
            get {
                object obj = ResourceManager.GetObject("Whisk_7a2731d0a50dfd5b1424fb307dcf5f16dr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_7af3eac3b10eebdbad6485e1d9a71c9bdr {
            get {
                object obj = ResourceManager.GetObject("Whisk_7af3eac3b10eebdbad6485e1d9a71c9bdr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_7d4409953bc0d76b679441bb050006fadr {
            get {
                object obj = ResourceManager.GetObject("Whisk_7d4409953bc0d76b679441bb050006fadr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_84374cf987abd289027437745415fc16dr {
            get {
                object obj = ResourceManager.GetObject("Whisk_84374cf987abd289027437745415fc16dr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_8479a259422cb13aa384fcab30cfc42adr {
            get {
                object obj = ResourceManager.GetObject("Whisk_8479a259422cb13aa384fcab30cfc42adr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_8d0be457adac59c9b034565f14d4192bdr {
            get {
                object obj = ResourceManager.GetObject("Whisk_8d0be457adac59c9b034565f14d4192bdr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_8f39277112fd307b03d4fc2d57204ca5dr {
            get {
                object obj = ResourceManager.GetObject("Whisk_8f39277112fd307b03d4fc2d57204ca5dr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_a8ae8f2288e0db49c3b42f3dcb4a165edr {
            get {
                object obj = ResourceManager.GetObject("Whisk_a8ae8f2288e0db49c3b42f3dcb4a165edr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_b31e7c93bc31ada80ac46f9bf45352dfdr {
            get {
                object obj = ResourceManager.GetObject("Whisk_b31e7c93bc31ada80ac46f9bf45352dfdr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_b431aa9608a8e569d7d4dd5bb8a1a18bdr {
            get {
                object obj = ResourceManager.GetObject("Whisk_b431aa9608a8e569d7d4dd5bb8a1a18bdr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_b9b95ee79604c0b91c44d0250172aa6adr {
            get {
                object obj = ResourceManager.GetObject("Whisk_b9b95ee79604c0b91c44d0250172aa6adr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_c556d621e533b8c9615450e8526761c8dr {
            get {
                object obj = ResourceManager.GetObject("Whisk_c556d621e533b8c9615450e8526761c8dr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_d6d536d0adb262c8ed24e4e327f35e7cdr {
            get {
                object obj = ResourceManager.GetObject("Whisk_d6d536d0adb262c8ed24e4e327f35e7cdr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Whisk_f4b8d3091f5472eb67a4df5b97e60128eg {
            get {
                object obj = ResourceManager.GetObject("Whisk_f4b8d3091f5472eb67a4df5b97e60128eg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
